FROM ubuntu:18.04

# Add files.
ADD C:/Users/hdecr/Documents/Prog/Hack1Robo /usr/local/aseba

# Install.
# RUN \
    # apt update
#   sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
#   apt-get update && \
#   apt-get -y upgrade && \
#   apt-get install -y build-essential && \
#   apt-get install -y software-properties-common && \
#   apt-get install -y byobu curl git htop man unzip vim wget && \
#   rm -rf /var/lib/apt/lists/*


# Set environment variables.
# ENV HOME /root

# Define working directory.
# WORKDIR /root

# Define default command.
# CMD ["bash"]
ENTRYPOINT ["tail", "-f", "/dev/null"]